CREATE TABLE IF NOT EXISTS predictions (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
  image_path TEXT NOT NULL,
  label TEXT NOT NULL,
  confidence REAL NOT NULL,
  advice TEXT NOT NULL
);